connector.name=kafka
kafka.nodes=kafka:29092
kafka.table-names=healthcare.patients
kafka.hide-internal-columns=false
kafka.key-decoder-name=avro
kafka.value-decoder-name=avro
kafka.confluent-schema-registry-url=http://schema-registry:8081
