connector.name=kafka

# Kafka broker
kafka.nodes=kafka:29092

# Expose Kafka metadata columns
kafka.hide-internal-columns=false

# Use Confluent Schema Registry
kafka.table-description-supplier=CONFLUENT
kafka.confluent-schema-registry-url=http://schema-registry:8081
